### ISSUE TITLE
Legacy metabolize weapon switch option doesn't work properly

### ISSUE THREAD

**Issue by keatsandyeats** [Mendasp/NS2Plus#83]
As of https://github.com/sclark39/NS2Plus/commit/c88d50e2f0044e9bc2f395399ebef2c520bad652, using the number keys (or whatever your binds are) to select Fade weapons causes your weapon to quickly switch back and forth between your current weapon and your selection. You will eventually end up on the weapon you selected. This flicker rarely doesn't happen with the option set to Default. With the option set to "use weapon slots", the flicker happens every time.

There is a lua error every time you weapon switch as fade, on a local server at least. Not sure about remote ones. Edit: this error happens regardless of the new setting or whether you use the movement modifier key or the weapon select keys.  https://gist.github.com/keatsandyeats/bfd877891e2e7acd610e05b94d76a184

**Comment by GhoulofGSG9** [comment]
Known issue as mentioned in the changelog. I have been trying to figure out how to propagate the option's value to the Predict World for the last 5 days. I will see if i can figure it out today, otherwise I'll just push a fix for the script error. But the "flicker" will still occur when switching to or from Metabolize while prediction is running.
